name: Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-light.svg?color_snake=#00A0E3&color_dots=#EBEDF0,#B3E5F5,#5CC8EC,#00A0E3,#0079AD
            dist/snake-dark.svg?color_snake=#00E5FF&color_dots=#151B23,#0B3A4A,#0E6A80,#00A8C6,#00E5FF

      - uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
